// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tronghieu_941.Models;

#nullable disable

namespace tronghieu_941.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tronghieu_941.Models.Nganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NganhHocs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenNganh = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = 2,
                            TenNganh = "Quản trị kinh doanh"
                        },
                        new
                        {
                            Id = 3,
                            TenNganh = "Du lịch"
                        });
                });

            modelBuilder.Entity("tronghieu_941.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Hinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MSVV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNganh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaNganh");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GioiTinh = "Nam",
                            Hinh = "/ImageSinhVien/default.jpg",
                            HoTen = "Nguyễn Văn A",
                            MSVV = "SV001",
                            MaNganh = 1,
                            NgaySinh = new DateTime(2002, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            GioiTinh = "Nữ",
                            Hinh = "/ImageSinhVien/default.jpg",
                            HoTen = "Trần Thị B",
                            MSVV = "SV002",
                            MaNganh = 2,
                            NgaySinh = new DateTime(2001, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("tronghieu_941.Models.SinhVien", b =>
                {
                    b.HasOne("tronghieu_941.Models.Nganh", "Nganh")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("tronghieu_941.Models.Nganh", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
